"""Add table alias

Revision ID: 25349345103a
Revises: 3ce414a0f0fa
Create Date: 2026-06-26 00:39:09.273273

"""
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25349345103a'
down_revision: str | Sequence[str] | None = '3ce414a0f0fa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('domain_id', sa.UUID(), nullable=False),
    sa.Column('local_part', sa.String(length=57), nullable=False),
    sa.Column('random_part', sa.String(length=6), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'FAILED', 'DELETING', name='aliasstatus', native_enum=False, create_constraint=True), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'local_part', 'random_part', name='uq_alias_domain_local_random')
    )
    with op.batch_alter_table('aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aliases_domain_id'), ['domain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aliases_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aliases_user_id'))
        batch_op.drop_index(batch_op.f('ix_aliases_domain_id'))

    op.drop_table('aliases')
    # ### end Alembic commands ###
